# Generated by Django 2.2.5 on 2019-09-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kap', '0003_amul_2_ltr_ice_cream_bricks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amul_1_Ltr_Ice_Cream_Tubs',
            new_name='One_Ltr_Ice_Cream_Tubs',
        ),
    ]
