# Generated by Django 2.2.5 on 2019-09-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kap', '0004_auto_20190929_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='One_Ltr_Ice_Cream_Tubs',
            new_name='Amul_1_Ltr_Ice_Cream_Tubs',
        ),
    ]
